# Modified from https://github.com/patrickloeber/python-github-action-template/tree/main
name: run github_pr_slack_bot.py

on:
  schedule:
    - cron: '*/5 * * * *' # At 12:20 AM each day UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SLACK_BOT_TOKEN:    ${{ secrets.SLACK_BOT_TOKEN }}
          API_TOKEN_GITHUB:   ${{ secrets.API_TOKEN_GITHUB }}
          OWNER_NAME_GITHUB:  ${{ secrets.OWNER_NAME_GITHUB }}

        run: python github_pr_slack_bot.py
